server:
  port: 8101
spring:
  application:
    name: 'playstation'

# ============================
# = Postgres DB configurations
# ============================
  datasource:
    url: jdbc:h2:~/playstation;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    username: sa
    password: ""
    driver-class-name: org.h2.Driver
    platform: h2
    initialization-mode: always
    continue-on-error: "true"
  jpa:
    genrate-ddl: "true"
    hibernate:
      ddl-auto: update
    show-sql: "true"
  jackson:
    parser:
      allow-single-quotes: "true"
  h2:
    console:
      enabled: "true"
      settings:
        web-allow-others: "true"

# =============================================
# = Logging configurations
# =============================================
logging:
  level:
    org:
      hibernate:
        stat: info
        type: info
    root: info
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{35} - %msg %n'
  file: 'logs/playstation.log'
  
